version: '3.1'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_USER=your_username
      - N8N_BASIC_AUTH_PASSWORD=your_password
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=your_postgres_host
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=your_database
      - DB_POSTGRESDB_USER=your_user
      - DB_POSTGRESDB_PASSWORD=your_password
    volumes:
      - ~/.n8n:/home/node/.n8n